/-
Generated by birdrat-proplogic.
Benchmark suite: small-targets

Lean checks this proof as a certificate for the internally generated P2 + CD proof.
Lean was not used to search for the proof.
-/

namespace BirdratOutput

theorem p2_ax1 (P Q : Prop) : P → Q → P :=
  fun hp _ => hp

theorem p2_ax2 (P Q R : Prop) :
    (P → Q → R) → (P → Q) → P → R :=
  fun hpqr hpq hp => hpqr hp (hpq hp)

theorem p2_ax3 (P Q : Prop) : (¬ P → ¬ Q) → Q → P := by
  classical
  intro h hq
  by_cases hp : P
  · exact hp
  · exact False.elim ((h hp) hq)

/-
Theorem: identity
Surface target: p → p
Core target: p → p
Found by: schema-instantiation
Phase: strict-preselected
CD steps: 2
CD depth: 2
Proof size: 5
-/
theorem identity (p : Prop) : (p → p) := by
  let M_q4_leaf3 : Prop := p
  have h1 : ((p → ((M_q4_leaf3 → p) → p)) → ((p → (M_q4_leaf3 → p)) → (p → p))) := p2_ax2 p ((M_q4_leaf3 → p)) p
  have h2 : (p → ((M_q4_leaf3 → p) → p)) := p2_ax1 p ((M_q4_leaf3 → p))
  have h3 : ((p → (M_q4_leaf3 → p)) → (p → p)) := h1 h2
  have h4 : (p → (M_q4_leaf3 → p)) := p2_ax1 p M_q4_leaf3
  have h5 : (p → p) := h3 h4
  exact h5

/-
Theorem: syllogism
Surface target: (p → q) → (r → p) → r → q
Core target: (p → q) → (r → p) → r → q
Found by: evolution
Phase: strict-preselected
CD steps: 3
CD depth: 3
Proof size: 7
-/
theorem syllogism (p : Prop) (q : Prop) (r : Prop) : ((p → q) → ((r → p) → (r → q))) := by
  have h1 : (((p → q) → ((r → (p → q)) → ((r → p) → (r → q)))) → (((p → q) → (r → (p → q))) → ((p → q) → ((r → p) → (r → q))))) := p2_ax2 ((p → q)) ((r → (p → q))) (((r → p) → (r → q)))
  have h2 : (((r → (p → q)) → ((r → p) → (r → q))) → ((p → q) → ((r → (p → q)) → ((r → p) → (r → q))))) := p2_ax1 (((r → (p → q)) → ((r → p) → (r → q)))) ((p → q))
  have h3 : ((r → (p → q)) → ((r → p) → (r → q))) := p2_ax2 r p q
  have h4 : ((p → q) → ((r → (p → q)) → ((r → p) → (r → q)))) := h2 h3
  have h5 : (((p → q) → (r → (p → q))) → ((p → q) → ((r → p) → (r → q)))) := h1 h4
  have h6 : ((p → q) → (r → (p → q))) := p2_ax1 ((p → q)) r
  have h7 : ((p → q) → ((r → p) → (r → q))) := h5 h6
  exact h7

/-
Theorem: classical_negation
Surface target: ¬p → p → q
Core target: ¬p → p → q
Found by: schema-instantiation
Phase: strict-preselected
CD steps: 3
CD depth: 3
Proof size: 7
-/
theorem classical_negation (p : Prop) (q : Prop) : ((¬ p) → (p → q)) := by
  have h1 : (((¬ p) → (((¬ q) → (¬ p)) → (p → q))) → (((¬ p) → ((¬ q) → (¬ p))) → ((¬ p) → (p → q)))) := p2_ax2 ((¬ p)) (((¬ q) → (¬ p))) ((p → q))
  have h2 : ((((¬ q) → (¬ p)) → (p → q)) → ((¬ p) → (((¬ q) → (¬ p)) → (p → q)))) := p2_ax1 ((((¬ q) → (¬ p)) → (p → q))) ((¬ p))
  have h3 : (((¬ q) → (¬ p)) → (p → q)) := p2_ax3 q p
  have h4 : ((¬ p) → (((¬ q) → (¬ p)) → (p → q))) := h2 h3
  have h5 : (((¬ p) → ((¬ q) → (¬ p))) → ((¬ p) → (p → q))) := h1 h4
  have h6 : ((¬ p) → ((¬ q) → (¬ p))) := p2_ax1 ((¬ p)) ((¬ q))
  have h7 : ((¬ p) → (p → q)) := h5 h6
  exact h7

/-
Theorem: contraction
Surface target: (p → p → q) → p → q
Core target: (p → p → q) → p → q
Found by: beam
Phase: strict-preselected
CD steps: 3
CD depth: 2
Proof size: 7
-/
theorem contraction (p : Prop) (q : Prop) : ((p → (p → q)) → (p → q)) := by
  have h1 : (((p → (p → q)) → ((p → p) → (p → q))) → (((p → (p → q)) → (p → p)) → ((p → (p → q)) → (p → q)))) := p2_ax2 ((p → (p → q))) ((p → p)) ((p → q))
  have h2 : ((p → (p → q)) → ((p → p) → (p → q))) := p2_ax2 p p q
  have h3 : (((p → (p → q)) → (p → p)) → ((p → (p → q)) → (p → q))) := h1 h2
  have h4 : ((p → ((p → q) → p)) → ((p → (p → q)) → (p → p))) := p2_ax2 p ((p → q)) p
  have h5 : (p → ((p → q) → p)) := p2_ax1 p ((p → q))
  have h6 : ((p → (p → q)) → (p → p)) := h4 h5
  have h7 : ((p → (p → q)) → (p → q)) := h3 h6
  exact h7

/-
Theorem: distribution_application
Surface target: (p → q) → (p → q → r) → p → r
Core target: (p → q) → (p → q → r) → p → r
Found by: evolution
Phase: strict-preselected
CD steps: 6
CD depth: 4
Proof size: 13
-/
theorem distribution_application (p : Prop) (q : Prop) (r : Prop) : ((p → q) → ((p → (q → r)) → (p → r))) := by
  let M_p4_leaf3 : Prop := p
  let M_q4_leaf3 : Prop := p
  have h1 : ((((p → q) → (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r)))) → (((p → q) → ((p → (q → r)) → (p → q))) → ((p → q) → ((p → (q → r)) → (p → r))))) → ((M_p4_leaf3 → (M_q4_leaf3 → M_p4_leaf3)) → (((p → q) → (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r)))) → (((p → q) → ((p → (q → r)) → (p → q))) → ((p → q) → ((p → (q → r)) → (p → r))))))) := p2_ax1 ((((p → q) → (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r)))) → (((p → q) → ((p → (q → r)) → (p → q))) → ((p → q) → ((p → (q → r)) → (p → r)))))) ((M_p4_leaf3 → (M_q4_leaf3 → M_p4_leaf3)))
  have h2 : (((p → q) → (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r)))) → (((p → q) → ((p → (q → r)) → (p → q))) → ((p → q) → ((p → (q → r)) → (p → r))))) := p2_ax2 ((p → q)) (((p → (q → r)) → (p → q))) (((p → (q → r)) → (p → r)))
  have h3 : ((M_p4_leaf3 → (M_q4_leaf3 → M_p4_leaf3)) → (((p → q) → (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r)))) → (((p → q) → ((p → (q → r)) → (p → q))) → ((p → q) → ((p → (q → r)) → (p → r)))))) := h1 h2
  have h4 : (M_p4_leaf3 → (M_q4_leaf3 → M_p4_leaf3)) := p2_ax1 M_p4_leaf3 M_q4_leaf3
  have h5 : (((p → q) → (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r)))) → (((p → q) → ((p → (q → r)) → (p → q))) → ((p → q) → ((p → (q → r)) → (p → r))))) := h3 h4
  have h6 : ((((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r))) → ((p → q) → (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r))))) := p2_ax1 ((((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r)))) ((p → q))
  have h7 : (((p → (q → r)) → ((p → q) → (p → r))) → (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r)))) := p2_ax2 ((p → (q → r))) ((p → q)) ((p → r))
  have h8 : ((p → (q → r)) → ((p → q) → (p → r))) := p2_ax2 p q r
  have h9 : (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r))) := h7 h8
  have h10 : ((p → q) → (((p → (q → r)) → (p → q)) → ((p → (q → r)) → (p → r)))) := h6 h9
  have h11 : (((p → q) → ((p → (q → r)) → (p → q))) → ((p → q) → ((p → (q → r)) → (p → r)))) := h5 h10
  have h12 : ((p → q) → ((p → (q → r)) → (p → q))) := p2_ax1 ((p → q)) ((p → (q → r)))
  have h13 : ((p → q) → ((p → (q → r)) → (p → r))) := h11 h12
  exact h13

#check identity
#check syllogism
#check classical_negation
#check contraction
#check distribution_application

end BirdratOutput
